# Generated by Django 6.1.1 on 2026-09-05 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attemptquestion',
            name='answer_format',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name='attemptquestion',
            name='expected_answer',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='attemptquestion',
            name='kind',
            field=models.CharField(choices=[('MCQ', 'Multiple choice'), ('BUSINESS', 'Business question')], default='MCQ', max_length=10),
        ),
        migrations.AddField(
            model_name='attemptquestion',
            name='steps',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='attemptquestion',
            name='tolerance',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='attemptquestion',
            name='typed_answer',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='attemptquestion',
            name='correct_index',
            field=models.IntegerField(default=-1),
        ),
    ]
