# Generated by Django 6.1.1 on 2026-09-10 10:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_chapter_published_at_chapter_review_comment_and_more'),
        ('quizzes', '0002_attemptquestion_answer_format_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_sets', to='courses.chapter')),
                ('module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_sets', to='courses.module')),
            ],
            options={
                'ordering': ['number'],
                'unique_together': {('chapter', 'module', 'number')},
            },
        ),
        migrations.CreateModel(
            name='SetAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.chapter')),
                ('module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.module')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='set_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('student', 'chapter', 'module')},
            },
        ),
        migrations.CreateModel(
            name='SetQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('kind', models.CharField(choices=[('MCQ', 'Multiple choice'), ('BUSINESS', 'Business question')], default='MCQ', max_length=10)),
                ('prompt', models.TextField()),
                ('options', models.JSONField(default=list)),
                ('correct_index', models.IntegerField(default=-1)),
                ('expected_answer', models.CharField(blank=True, max_length=120)),
                ('answer_format', models.CharField(blank=True, max_length=12)),
                ('tolerance', models.FloatField(default=0)),
                ('steps', models.CharField(blank=True, max_length=250)),
                ('explanation', models.TextField(blank=True)),
                ('skill', models.CharField(blank=True, max_length=80)),
                ('workbook', models.JSONField(default=dict)),
                ('edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_questions', to=settings.AUTH_USER_MODEL)),
                ('question_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quizzes.questionset')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('question_set', 'order')},
            },
        ),
    ]
