# Generated by Django 6.1.1 on 2026-09-10 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_chapter_published_at_chapter_review_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rubric',
            name='tracks_progress',
            field=models.BooleanField(default=True),
        ),
    ]
