# Generated by Django 6.1.1 on 2026-09-22 11:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_bookimage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('kind', models.CharField(choices=[('COURSE_ACCESS', 'Course access'), ('APPROVAL_REQUEST', 'Approval request'), ('APPROVAL_RESULT', 'Approval result'), ('PUBLISHED', 'Material published'), ('EVALUATION', 'Evaluation given'), ('FEEDBACK', 'Student feedback'), ('SYSTEM', 'System')], default='SYSTEM', max_length=24)),
                ('link_path', models.CharField(blank=True, max_length=250)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
